apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metaarch-ingress
  namespace: metaarch
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: gateway.metaarch.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metaarch-api-gateway
                port:
                  name: http
    - host: grafana.metaarch.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  name: http
    - host: kibana.metaarch.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana
                port:
                  name: http
