apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config.yaml
  - mysql.yaml
  - kafka.yaml
  - observability.yaml
  - applications.yaml
  - alerts-service.yaml
  - monitoring.yaml
