input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if ![service] and [app_name] {
    mutate {
      add_field => { "service" => "%{[app_name]}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "microservices-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
